<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-BHR3PSD" failures="3" tests="12" name="testNgPack.VerifyForgotPasswordFunctionality" time="62.356" errors="0" timestamp="2024-02-28T15:55:53 IST" skipped="0">
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifyTextOnForgotPasswordPage" time="5.908"/>
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifyTextOnForgotPasswordPage" time="3.428"/>
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifyTextOnForgotPasswordPage" time="4.154"/>
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifyCancelButtonOnForgotPasswordPage" time="4.309"/>
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifyCancelButtonOnForgotPasswordPage" time="3.306"/>
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifyCancelButtonOnForgotPasswordPage" time="2.719"/>
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifySearchButtonFunctionalityWithWrongId" time="6.334"/>
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifySearchButtonFunctionalityWithWrongId" time="6.045"/>
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifySearchButtonFunctionalityWithWrongId" time="5.593"/>
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifySearchButtonFunctionalityWithCorrectId" time="7.104">
    <failure message="expected [Log in to Facebook..] but found [Log in to Facebook]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Log in to Facebook..] but found [Log in to Facebook]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testNgPack.VerifyForgotPasswordFunctionality.verifySearchButtonFunctionalityWithCorrectId(VerifyForgotPasswordFunctionality.java:134)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifySearchButtonFunctionalityWithCorrectId -->
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifySearchButtonFunctionalityWithCorrectId" time="9.010">
    <failure message="expected [Log in to Facebook..] but found [Log in to Facebook]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Log in to Facebook..] but found [Log in to Facebook]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testNgPack.VerifyForgotPasswordFunctionality.verifySearchButtonFunctionalityWithCorrectId(VerifyForgotPasswordFunctionality.java:134)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifySearchButtonFunctionalityWithCorrectId -->
  <testcase classname="testNgPack.VerifyForgotPasswordFunctionality" name="verifySearchButtonFunctionalityWithCorrectId" time="4.446">
    <failure message="expected [Log in to Facebook..] but found [Log in to Facebook]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Log in to Facebook..] but found [Log in to Facebook]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testNgPack.VerifyForgotPasswordFunctionality.verifySearchButtonFunctionalityWithCorrectId(VerifyForgotPasswordFunctionality.java:134)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifySearchButtonFunctionalityWithCorrectId -->
</testsuite> <!-- testNgPack.VerifyForgotPasswordFunctionality -->
